*** Settings ***
Documentation    Arquivo de status das API's do Academy - QA Coders

*** Variables ***
${OK}                 200
${Created}            201
${Accepted}           202
${NoContent}          204
${BadRequest}         400
${Unauthorized}       401
${Forbidden}          403
${NotFound}           404
${RequestTimeout}     408
${Conflict}           409
${ServerError}        500
${BadGateway}         502             
${ServiceUnav}        503